# Site settings
title: Homepage
name: STELLA PARK
copyright: STELLA PARK ⓒ 2016
email: pmhwa77@naver.com
hp: +82.10.3224.1411
address: Seoul.South Korea
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://edenyoon.github.io" # the base hostname & protocol for your site
facebook_username: mihwa.park.311
pinterest_username: pmhwa77
behance_username: mihwa
instagram_username: pmhwa77

# Build settings
markdown: kramdown
permalink: pretty
